### ISSUE TITLE
Testing in Visual Studio 2019

### ISSUE THREAD

**Issue by SonaBIMDev** [openE57/openE57-sample-project#1]
H madduci, thx for putting this post : 
I've got a question, after step 2, on step 3, do I have to run a Developper command Prompt and where to run the commands?
Thx

**Comment by madduci** [comment]
Yes, try to run the commands always in the developer command prompt

**Comment by SonaBIMDev** [comment]
Thx, 

I pt the conanfl.txt (just pebore the openE57 directory) containing this : 

`[requires]
boost/1.77.0
icu/70.1
xerces-c/3.2.3

[generators]
cmake_find_package

[options]
boost:multithreading=True
boost:shared=False
icu:shared=False
xerces-c:shared=False
`
I run the first commands and I've got this : 

![image](https://user-images.githubusercontent.com/54843266/152367119-98d24553-1d50-4359-b1dd-d75bac47d3f7.png)

But, after that, I run the others commands and I've got errors : 
![screenshot_184](https://user-images.githubusercontent.com/54843266/152367291-c1eb59ba-a838-443e-b9b4-616d2e7b35ca.png)

And here is my VSStudio error whenI compile...
![screenshot_185](https://user-images.githubusercontent.com/54843266/152367409-e33e0682-0f06-4f8d-bb2c-071884643d5d.png)

I'm lost...Sorry

**Comment by madduci** [comment]
Hi

thanks for your patience. I'm refactoring the openE57, so it will be easier to be used with this or other projects. All my efforts are done in my spare time, please be patient, I'll try to resolve it soon

**Comment by SonaBIMDev** [comment]
Fabulous Madduci! Great...Take care..

**Comment by madduci** [comment]
Resolved here https://github.com/openE57/openE57/issues/22
